language: ruby
sudo: false
script: 'bundle exec rake test:coverage --trace && bundle exec rubocop'
rvm:
  - 2.3.3
  - jruby-9.1.5.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
